### PR TITLE
fix: Append Object Modifier for "s3:GetObject"

### PR DESCRIPTION
**Pull request by kylegoch**
## Description
Change the IAM Resource to apply to the objects in the bucket. (`/*` required)

## Motivation and Context
The DD Lambda will throw an access denied error as is. Adding `/*` in the IAM policy resolves this issue, as `s3:GetObject` is an object level action, and thus the lambda needs access to the objects.

## How Has This Been Tested?
Tested locally, by applying to my DD Log Forwarder setup to confirm the IAM policy appeared correctly.

### CODE REVIEW

**Comment by kylegoch** [comment]
Sorry for the extemporaneous commits. Thats what I get for trying to do this in the GH UI.

**Comment by bryantbiggs** [comment]
hi @kylegoch - thanks for the PR! I think the way the module is written allows for the most flexibility and avoids making assumptions. meaning, if we accept this change, then all users are forced into a convention. I think to solve your situation, the best route would be to pass in the `*` where you see fit for your use case. for example:

```hcl
	s3_log_bucket_arns = ["arn:aws:s3:::my_bucket/*", "arn:aws:s3:::sensitive_bucket/some/prefix/*"]
```

you can pass in the bucket ARN scoped with the level of access you wish to permit for the log forwarder. some users will be ok with giving access to the whole bucket, but its quite common for users to want to give only limited access to a specific prefix. I hope this helps clarify things

**Comment by kylegoch** [comment]
Interesting. I would maybe add a line in the docs/Readme on that. I assumed if gave the module the ARN it would take care of the rest. Its a super easy fix on my end to add `/*` to the ARN list. Just wasnt aware I needed to until I went digging.

**Comment by bryantbiggs** [comment]
yes you're right @kylegoch - I can add something in to demonstrate/highlight this

**Pull request closed without merging**
